window.I18N = window.I18N || {};
window.I18N.ar = {
  eyebrow: 'لوحة تنظيم العمل',
  title: 'إدارة مهام المبرمجين',
  assistantTitle: 'المساعد الذكي',
  apiKeyLabel: 'مفتاح API',
  apiKeyPlaceholder: 'أدخل مفتاح API إن وجد',
  promptPlaceholder: 'اكتب طلبك...',
  askBtn: 'اسأل المساعد',
  suggestBtn: 'اقتراح مهام',
  assistantDefaultResponse: 'سأساعدك في تنظيم المهام وتخطيط التنفيذ.',
  addTaskTitle: 'إضافة مهمة جديدة',
  taskTitleLabel: 'عنوان المهمة',
  taskTitlePlaceholder: 'مثال: إصلاح خطأ في واجهة الدفع',
  taskDescriptionLabel: 'الوصف',
  taskDescriptionPlaceholder: 'اكتب تفاصيل المهمة أو النتيجة المطلوبة...',
  priorityLabel: 'الأولوية',
  priorityHigh: 'عالية',
  priorityMedium: 'متوسطة',
  priorityLow: 'منخفضة',
  categoryLabel: 'الفئة',
  categoryFeature: 'ميزة',
  categoryBug: 'خطأ',
  categoryResearch: 'بحث',
  categoryTest: 'اختبار',
  categoryRefactor: 'إعادة هيكلة',
  dueDateLabel: 'تاريخ الاستحقاق',
  addTaskBtn: 'إضافة المهمة',
  taskListTitle: 'قائمة المهام',
  searchPlaceholder: 'بحث سريع...',
  filterAll: 'الكل',
  filterPending: 'قيد التنفيذ',
  filterDone: 'مكتملة',
  filterHigh: 'أولوية عالية',
  statTotal: 'إجمالي',
  statDone: 'مكتملة',
  statPending: 'متبقية',
  statProgress: 'نسبة الإنجاز',
  emptyStateTitle: 'لا توجد مهام تطابق البحث الحالي',
  emptyStateText: 'جرّب فئة أخرى أو أضف مهمة جديدة.',
  noDescription: 'لا يوجد وصف إضافي.',
  noDate: 'بدون تاريخ',
  completeTask: 'إكمال',
  reopenTask: 'إعادة فتح',
  deleteTask: 'حذف',
  toggleAria: 'تغيير حالة المهمة',
  languageLabel: 'اللغة',
  other: 'أخرى',
  noTasks: 'لا توجد مهام',
  currentTasks: 'المهام الحالية',
  askFirst: 'اكتب سؤالاً أو طلباً أولاً.',
  preparingAssistant: 'جارٍ تجهيز إجابة المساعد...',
  assistantUnavailable: 'تعذر الاتصال بالمساعد في الوقت الحالي، وستستخدم النسخة المحلية.',
  shareDataBtn: 'مشاركة البيانات',
  shareNoTasks: 'لا توجد مهام للمشاركة.',
  shareLinkCopied: 'تم نسخ رابط المشاركة بنجاح.',
  shareLinkLabel: 'رابط المشاركة',
};
