window.I18N = window.I18N || {};
window.I18N.en = {
  eyebrow: 'Work Board',
  title: 'Programmer Tasks Manager',
  assistantTitle: 'AI Assistant',
  apiKeyLabel: 'API Key',
  apiKeyPlaceholder: 'Enter API key if available',
  promptPlaceholder: 'Write your request...',
  askBtn: 'Ask Assistant',
  suggestBtn: 'Task Suggestions',
  assistantDefaultResponse: 'I will help you organize tasks and plan execution.',
  addTaskTitle: 'Add New Task',
  taskTitleLabel: 'Task Title',
  taskTitlePlaceholder: 'Example: Fix payment UI bug',
  taskDescriptionLabel: 'Description',
  taskDescriptionPlaceholder: 'Write details about the task or desired result...',
  priorityLabel: 'Priority',
  priorityHigh: 'High',
  priorityMedium: 'Medium',
  priorityLow: 'Low',
  categoryLabel: 'Category',
  categoryFeature: 'Feature',
  categoryBug: 'Bug',
  categoryResearch: 'Research',
  categoryTest: 'Test',
  categoryRefactor: 'Refactor',
  dueDateLabel: 'Due Date',
  addTaskBtn: 'Add Task',
  taskListTitle: 'Task List',
  searchPlaceholder: 'Quick search...',
  filterAll: 'All',
  filterPending: 'In Progress',
  filterDone: 'Completed',
  filterHigh: 'High Priority',
  statTotal: 'Total',
  statDone: 'Completed',
  statPending: 'Remaining',
  statProgress: 'Progress',
  emptyStateTitle: 'No tasks match the current search',
  emptyStateText: 'Try another category or add a new task.',
  noDescription: 'No additional description.',
  noDate: 'No date',
  completeTask: 'Complete',
  reopenTask: 'Reopen',
  deleteTask: 'Delete',
  toggleAria: 'Toggle task status',
  languageLabel: 'Language',
  other: 'Other',
  noTasks: 'No tasks',
  currentTasks: 'Current tasks',
  askFirst: 'Write your question or request first.',
  preparingAssistant: 'Preparing the assistant response...',
  assistantUnavailable: 'The assistant is unavailable right now, so the local version will be used.',
  shareDataBtn: 'Share data',
  shareNoTasks: 'There are no tasks to share.',
  shareLinkCopied: 'The share link was copied successfully.',
  shareLinkLabel: 'Share link',
};
