window.I18N = window.I18N || {};
window.I18N.es = {
  eyebrow: 'Panel de trabajo',
  title: 'Gestor de tareas del programador',
  assistantTitle: 'Asistente de IA',
  apiKeyLabel: 'Clave API',
  apiKeyPlaceholder: 'Introduce la clave API si existe',
  promptPlaceholder: 'Escribe tu solicitud...',
  askBtn: 'Preguntar al asistente',
  suggestBtn: 'Sugerencias de tareas',
  assistantDefaultResponse: 'Te ayudaré a organizar las tareas y planificar la ejecución.',
  addTaskTitle: 'Agregar nueva tarea',
  taskTitleLabel: 'Título de la tarea',
  taskTitlePlaceholder: 'Ejemplo: corregir error en la interfaz de pago',
  taskDescriptionLabel: 'Descripción',
  taskDescriptionPlaceholder: 'Escribe los detalles de la tarea o el resultado deseado...',
  priorityLabel: 'Prioridad',
  priorityHigh: 'Alta',
  priorityMedium: 'Media',
  priorityLow: 'Baja',
  categoryLabel: 'Categoría',
  categoryFeature: 'Función',
  categoryBug: 'Error',
  categoryResearch: 'Investigación',
  categoryTest: 'Prueba',
  categoryRefactor: 'Refactorización',
  dueDateLabel: 'Fecha de vencimiento',
  addTaskBtn: 'Agregar tarea',
  taskListTitle: 'Lista de tareas',
  searchPlaceholder: 'Búsqueda rápida...',
  filterAll: 'Todo',
  filterPending: 'En progreso',
  filterDone: 'Completado',
  filterHigh: 'Prioridad alta',
  statTotal: 'Total',
  statDone: 'Completado',
  statPending: 'Restante',
  statProgress: 'Progreso',
  emptyStateTitle: 'No hay tareas que coincidan con la búsqueda actual',
  emptyStateText: 'Prueba otra categoría o agrega una tarea nueva.',
  noDescription: 'Sin descripción adicional.',
  noDate: 'Sin fecha',
  completeTask: 'Completar',
  reopenTask: 'Reabrir',
  deleteTask: 'Eliminar',
  toggleAria: 'Cambiar el estado de la tarea',
  languageLabel: 'Idioma',
  other: 'Otro',
  noTasks: 'Sin tareas',
  currentTasks: 'Tareas actuales',
  askFirst: 'Primero escribe tu pregunta o solicitud.',
  preparingAssistant: 'Preparando la respuesta del asistente...',
  assistantUnavailable: 'El asistente no está disponible en este momento, se usará la versión local.',
};
