window.I18N = window.I18N || {};
window.I18N.fr = {
  eyebrow: 'Tableau de travail',
  title: 'Gestion des tâches du programmeur',
  assistantTitle: 'Assistant IA',
  apiKeyLabel: 'Clé API',
  apiKeyPlaceholder: 'Entrez la clé API si disponible',
  promptPlaceholder: 'Écrivez votre demande...',
  askBtn: 'Demander à l’assistant',
  suggestBtn: 'Suggestions de tâches',
  assistantDefaultResponse: 'Je vous aiderai à organiser les tâches et à planifier l’exécution.',
  addTaskTitle: 'Ajouter une nouvelle tâche',
  taskTitleLabel: 'Titre de la tâche',
  taskTitlePlaceholder: 'Exemple : Corriger le bug de l’interface de paiement',
  taskDescriptionLabel: 'Description',
  taskDescriptionPlaceholder: 'Décrivez les détails de la tâche ou le résultat souhaité...',
  priorityLabel: 'Priorité',
  priorityHigh: 'Élevée',
  priorityMedium: 'Moyenne',
  priorityLow: 'Faible',
  categoryLabel: 'Catégorie',
  categoryFeature: 'Fonctionnalité',
  categoryBug: 'Bug',
  categoryResearch: 'Recherche',
  categoryTest: 'Test',
  categoryRefactor: 'Refactorisation',
  dueDateLabel: 'Date d’échéance',
  addTaskBtn: 'Ajouter la tâche',
  taskListTitle: 'Liste des tâches',
  searchPlaceholder: 'Recherche rapide...',
  filterAll: 'Tout',
  filterPending: 'En cours',
  filterDone: 'Terminé',
  filterHigh: 'Priorité élevée',
  statTotal: 'Total',
  statDone: 'Terminé',
  statPending: 'Restant',
  statProgress: 'Progression',
  emptyStateTitle: 'Aucune tâche ne correspond à la recherche actuelle',
  emptyStateText: 'Essayez une autre catégorie ou ajoutez une nouvelle tâche.',
  noDescription: 'Aucune description supplémentaire.',
  noDate: 'Sans date',
  completeTask: 'Terminer',
  reopenTask: 'Rouvrir',
  deleteTask: 'Supprimer',
  toggleAria: 'Changer le statut de la tâche',
  languageLabel: 'Langue',
  other: 'Autre',
  noTasks: 'Aucune tâche',
  currentTasks: 'Tâches actuelles',
  askFirst: 'Écrivez d’abord votre question ou votre demande.',
  preparingAssistant: 'Préparation de la réponse de l’assistant...',
  assistantUnavailable: 'L’assistant est indisponible pour le moment, la version locale sera utilisée.',
};
