window.I18N = window.I18N || {};
window.I18N.hi = {
  eyebrow: 'कार्य बोर्ड',
  title: 'प्रोग्रामर टास्क मैनेजर',
  assistantTitle: 'AI सहायक',
  apiKeyLabel: 'API कुंजी',
  apiKeyPlaceholder: 'अगर उपलब्ध हो तो API कुंजी डालें',
  promptPlaceholder: 'अपना अनुरोध लिखें...',
  askBtn: 'सहायक से पूछें',
  suggestBtn: 'टास्क सुझाव',
  assistantDefaultResponse: 'मैं आपके कार्यों को व्यवस्थित करने और निष्पादन की योजना बनाने में मदद करूंगा।',
  addTaskTitle: 'नया कार्य जोड़ें',
  taskTitleLabel: 'कार्य का शीर्षक',
  taskTitlePlaceholder: 'उदाहरण: भुगतान UI में बग ठीक करें',
  taskDescriptionLabel: 'विवरण',
  taskDescriptionPlaceholder: 'कार्य का विवरण या वांछित परिणाम लिखें...',
  priorityLabel: 'प्राथमिकता',
  priorityHigh: 'उच्च',
  priorityMedium: 'मध्यम',
  priorityLow: 'कम',
  categoryLabel: 'श्रेणी',
  categoryFeature: 'फ़ीचर',
  categoryBug: 'बग',
  categoryResearch: 'अनुसंधान',
  categoryTest: 'परीक्षण',
  categoryRefactor: 'रीफ़ैक्टर',
  dueDateLabel: 'अवधि तिथि',
  addTaskBtn: 'कार्य जोड़ें',
  taskListTitle: 'कार्य सूची',
  searchPlaceholder: 'त्वरित खोज...',
  filterAll: 'सभी',
  filterPending: 'चालू',
  filterDone: 'पूर्ण',
  filterHigh: 'उच्च प्राथमिकता',
  statTotal: 'कुल',
  statDone: 'पूर्ण',
  statPending: 'बाकी',
  statProgress: 'प्रगति',
  emptyStateTitle: 'वर्तमान खोज से मेल खाने वाला कोई कार्य नहीं है',
  emptyStateText: 'दूसरी श्रेणी आज़माएँ या नया कार्य जोड़ें।',
  noDescription: 'कोई अतिरिक्त विवरण नहीं।',
  noDate: 'तारीख नहीं',
  completeTask: 'पूर्ण करें',
  reopenTask: 'दोबारा खोलें',
  deleteTask: 'हटाएँ',
  toggleAria: 'कार्य स्थिति बदलें',
  languageLabel: 'भाषा',
  other: 'अन्य',
  noTasks: 'कोई कार्य नहीं',
  currentTasks: 'वर्तमान कार्य',
  askFirst: 'पहले अपना प्रश्न या अनुरोध लिखें।',
  preparingAssistant: 'सहायक का उत्तर तैयार किया जा रहा है...',
  assistantUnavailable: 'सहायक वर्तमान में उपलब्ध नहीं है, इसलिए लोकल संस्करण उपयोग में होगा।',
};
