window.I18N = window.I18N || {};
window.I18N.it = {
  eyebrow: 'Pannello di lavoro',
  title: 'Gestore attività del programmatore',
  assistantTitle: 'Assistente AI',
  apiKeyLabel: 'Chiave API',
  apiKeyPlaceholder: 'Inserisci la chiave API, se disponibile',
  promptPlaceholder: 'Scrivi la tua richiesta...',
  askBtn: 'Chiedi all’assistente',
  suggestBtn: 'Suggerimenti per le attività',
  assistantDefaultResponse: 'Ti aiuterò a organizzare le attività e a pianificare l’esecuzione.',
  addTaskTitle: 'Aggiungi nuova attività',
  taskTitleLabel: 'Titolo dell’attività',
  taskTitlePlaceholder: 'Esempio: correggi bug nell’interfaccia di pagamento',
  taskDescriptionLabel: 'Descrizione',
  taskDescriptionPlaceholder: 'Scrivi i dettagli dell’attività o il risultato desiderato...',
  priorityLabel: 'Priorità',
  priorityHigh: 'Alta',
  priorityMedium: 'Media',
  priorityLow: 'Bassa',
  categoryLabel: 'Categoria',
  categoryFeature: 'Funzionalità',
  categoryBug: 'Bug',
  categoryResearch: 'Ricerca',
  categoryTest: 'Test',
  categoryRefactor: 'Refactor',
  dueDateLabel: 'Data di scadenza',
  addTaskBtn: 'Aggiungi attività',
  taskListTitle: 'Elenco attività',
  searchPlaceholder: 'Ricerca rapida...',
  filterAll: 'Tutte',
  filterPending: 'In corso',
  filterDone: 'Completate',
  filterHigh: 'Priorità alta',
  statTotal: 'Totale',
  statDone: 'Completate',
  statPending: 'Rimanenti',
  statProgress: 'Avanzamento',
  emptyStateTitle: 'Nessuna attività corrisponde alla ricerca attuale',
  emptyStateText: 'Prova un’altra categoria o aggiungi una nuova attività.',
  noDescription: 'Nessuna descrizione aggiuntiva.',
  noDate: 'Senza data',
  completeTask: 'Completa',
  reopenTask: 'Riapri',
  deleteTask: 'Elimina',
  toggleAria: 'Cambia stato dell’attività',
  languageLabel: 'Lingua',
  other: 'Altro',
  noTasks: 'Nessuna attività',
  currentTasks: 'Attività attuali',
  askFirst: 'Prima scrivi la tua domanda o richiesta.',
  preparingAssistant: 'Preparazione della risposta dell’assistente...',
  assistantUnavailable: 'L’assistente non è disponibile al momento, verrà usata la versione locale.',
};
