window.I18N = window.I18N || {};
window.I18N.ko = {
  eyebrow: '작업 보드',
  title: '프로그래머 작업 관리자',
  assistantTitle: 'AI 도우미',
  apiKeyLabel: 'API 키',
  apiKeyPlaceholder: 'API 키를 입력하세요(있는 경우)',
  promptPlaceholder: '요청을 입력하세요...',
  askBtn: '도우미에게 물어보기',
  suggestBtn: '작업 제안',
  assistantDefaultResponse: '작업을 정리하고 실행 계획을 세우는 데 도와드릴게요.',
  addTaskTitle: '새 작업 추가',
  taskTitleLabel: '작업 제목',
  taskTitlePlaceholder: '예: 결제 UI 버그 수정',
  taskDescriptionLabel: '설명',
  taskDescriptionPlaceholder: '작업 세부사항 또는 원하는 결과를 적어주세요...',
  priorityLabel: '우선순위',
  priorityHigh: '높음',
  priorityMedium: '보통',
  priorityLow: '낮음',
  categoryLabel: '카테고리',
  categoryFeature: '기능',
  categoryBug: '버그',
  categoryResearch: '연구',
  categoryTest: '테스트',
  categoryRefactor: '리팩터링',
  dueDateLabel: '마감일',
  addTaskBtn: '작업 추가',
  taskListTitle: '작업 목록',
  searchPlaceholder: '빠른 검색...',
  filterAll: '전체',
  filterPending: '진행 중',
  filterDone: '완료',
  filterHigh: '높은 우선순위',
  statTotal: '전체',
  statDone: '완료',
  statPending: '남음',
  statProgress: '진행률',
  emptyStateTitle: '현재 검색 조건에 맞는 작업이 없습니다',
  emptyStateText: '다른 카테고리를 시도하거나 새 작업을 추가해보세요.',
  noDescription: '추가 설명이 없습니다.',
  noDate: '날짜 없음',
  completeTask: '완료',
  reopenTask: '다시 열기',
  deleteTask: '삭제',
  toggleAria: '작업 상태 변경',
  languageLabel: '언어',
  other: '기타',
  noTasks: '작업 없음',
  currentTasks: '현재 작업',
  askFirst: '먼저 질문이나 요청을 적어주세요.',
  preparingAssistant: '도우미 응답을 준비하는 중...',
  assistantUnavailable: '도우미를 사용할 수 없어서 로컬 버전을 사용합니다.',
};
