window.I18N = window.I18N || {};
window.I18N.pt = {
  eyebrow: 'Painel de trabalho',
  title: 'Gerenciador de tarefas do programador',
  assistantTitle: 'Assistente de IA',
  apiKeyLabel: 'Chave da API',
  apiKeyPlaceholder: 'Digite a chave da API, se existir',
  promptPlaceholder: 'Escreva sua solicitação...',
  askBtn: 'Perguntar ao assistente',
  suggestBtn: 'Sugestões de tarefas',
  assistantDefaultResponse: 'Vou ajudar a organizar as tarefas e planejar a execução.',
  addTaskTitle: 'Adicionar nova tarefa',
  taskTitleLabel: 'Título da tarefa',
  taskTitlePlaceholder: 'Exemplo: corrigir erro na interface de pagamento',
  taskDescriptionLabel: 'Descrição',
  taskDescriptionPlaceholder: 'Descreva os detalhes da tarefa ou o resultado desejado...',
  priorityLabel: 'Prioridade',
  priorityHigh: 'Alta',
  priorityMedium: 'Média',
  priorityLow: 'Baixa',
  categoryLabel: 'Categoria',
  categoryFeature: 'Recurso',
  categoryBug: 'Erro',
  categoryResearch: 'Pesquisa',
  categoryTest: 'Teste',
  categoryRefactor: 'Refatoração',
  dueDateLabel: 'Data de vencimento',
  addTaskBtn: 'Adicionar tarefa',
  taskListTitle: 'Lista de tarefas',
  searchPlaceholder: 'Pesquisa rápida...',
  filterAll: 'Todos',
  filterPending: 'Em andamento',
  filterDone: 'Concluído',
  filterHigh: 'Alta prioridade',
  statTotal: 'Total',
  statDone: 'Concluído',
  statPending: 'Restante',
  statProgress: 'Progresso',
  emptyStateTitle: 'Nenhuma tarefa corresponde à pesquisa atual',
  emptyStateText: 'Tente outra categoria ou adicione uma nova tarefa.',
  noDescription: 'Sem descrição adicional.',
  noDate: 'Sem data',
  completeTask: 'Concluir',
  reopenTask: 'Reabrir',
  deleteTask: 'Excluir',
  toggleAria: 'Alternar status da tarefa',
  languageLabel: 'Idioma',
  other: 'Outro',
  noTasks: 'Sem tarefas',
  currentTasks: 'Tarefas atuais',
  askFirst: 'Primeiro escreva sua pergunta ou solicitação.',
  preparingAssistant: 'Preparando a resposta do assistente...',
  assistantUnavailable: 'O assistente está indisponível no momento, então será usada a versão local.',
};
