window.I18N = window.I18N || {};
window.I18N.ru = {
  eyebrow: 'Рабочая панель',
  title: 'Менеджер задач программиста',
  assistantTitle: 'ИИ-ассистент',
  apiKeyLabel: 'API-ключ',
  apiKeyPlaceholder: 'Введите API-ключ, если он есть',
  promptPlaceholder: 'Напишите ваш запрос...',
  askBtn: 'Спросить ассистента',
  suggestBtn: 'Предложения задач',
  assistantDefaultResponse: 'Я помогу организовать задачи и спланировать выполнение.',
  addTaskTitle: 'Добавить новую задачу',
  taskTitleLabel: 'Название задачи',
  taskTitlePlaceholder: 'Например: исправить ошибку в интерфейсе оплаты',
  taskDescriptionLabel: 'Описание',
  taskDescriptionPlaceholder: 'Опишите детали задачи или желаемый результат...',
  priorityLabel: 'Приоритет',
  priorityHigh: 'Высокий',
  priorityMedium: 'Средний',
  priorityLow: 'Низкий',
  categoryLabel: 'Категория',
  categoryFeature: 'Функция',
  categoryBug: 'Ошибка',
  categoryResearch: 'Исследование',
  categoryTest: 'Тест',
  categoryRefactor: 'Рефакторинг',
  dueDateLabel: 'Срок выполнения',
  addTaskBtn: 'Добавить задачу',
  taskListTitle: 'Список задач',
  searchPlaceholder: 'Быстрый поиск...',
  filterAll: 'Все',
  filterPending: 'В процессе',
  filterDone: 'Готово',
  filterHigh: 'Высокий приоритет',
  statTotal: 'Всего',
  statDone: 'Готово',
  statPending: 'Осталось',
  statProgress: 'Прогресс',
  emptyStateTitle: 'Нет задач, соответствующих текущему поиску',
  emptyStateText: 'Попробуйте другую категорию или добавьте новую задачу.',
  noDescription: 'Дополнительного описания нет.',
  noDate: 'Без даты',
  completeTask: 'Завершить',
  reopenTask: 'Открыть снова',
  deleteTask: 'Удалить',
  toggleAria: 'Изменить статус задачи',
  languageLabel: 'Язык',
  other: 'Другое',
  noTasks: 'Нет задач',
  currentTasks: 'Текущие задачи',
  askFirst: 'Сначала напишите вопрос или запрос.',
  preparingAssistant: 'Подготавливается ответ ассистента...',
  assistantUnavailable: 'Ассистент сейчас недоступен, будет использована локальная версия.',
};
