window.I18N = window.I18N || {};
window.I18N.tr = {
  eyebrow: 'İş paneli',
  title: 'Programcı Görev Yöneticisi',
  assistantTitle: 'Yapay Zeka Asistanı',
  apiKeyLabel: 'API Anahtarı',
  apiKeyPlaceholder: 'Varsa API anahtarını girin',
  promptPlaceholder: 'İsteğinizi yazın...',
  askBtn: 'Asistanı sor',
  suggestBtn: 'Görev önerileri',
  assistantDefaultResponse: 'Görevleri organize etmenize ve uygulama planlamasına yardımcı olacağım.',
  addTaskTitle: 'Yeni görev ekle',
  taskTitleLabel: 'Görev başlığı',
  taskTitlePlaceholder: 'Örnek: Ödeme arayüzünde hatayı düzelt',
  taskDescriptionLabel: 'Açıklama',
  taskDescriptionPlaceholder: 'Görev detaylarını veya istenen sonucu yazın...',
  priorityLabel: 'Öncelik',
  priorityHigh: 'Yüksek',
  priorityMedium: 'Orta',
  priorityLow: 'Düşük',
  categoryLabel: 'Kategori',
  categoryFeature: 'Özellik',
  categoryBug: 'Hata',
  categoryResearch: 'Araştırma',
  categoryTest: 'Test',
  categoryRefactor: 'Yeniden düzenleme',
  dueDateLabel: 'Bitiş tarihi',
  addTaskBtn: 'Görevi ekle',
  taskListTitle: 'Görev listesi',
  searchPlaceholder: 'Hızlı arama...',
  filterAll: 'Tümü',
  filterPending: 'Devam ediyor',
  filterDone: 'Tamamlandı',
  filterHigh: 'Yüksek öncelik',
  statTotal: 'Toplam',
  statDone: 'Tamamlandı',
  statPending: 'Kalan',
  statProgress: 'İlerleme',
  emptyStateTitle: 'Mevcut aramaya uygun görev yok',
  emptyStateText: 'Başka bir kategori deneyin veya yeni bir görev ekleyin.',
  noDescription: 'Ek açıklama yok.',
  noDate: 'Tarih yok',
  completeTask: 'Tamamla',
  reopenTask: 'Yeniden aç',
  deleteTask: 'Sil',
  toggleAria: 'Görev durumunu değiştir',
  languageLabel: 'Dil',
  other: 'Diğer',
  noTasks: 'Görev yok',
  currentTasks: 'Mevcut görevler',
  askFirst: 'Önce sorunuz veya isteğinizi yazın.',
  preparingAssistant: 'Asistan cevabı hazırlanıyor...',
  assistantUnavailable: 'Asistan şu anda kullanılamıyor, yerel sürüm kullanılacak.',
};
