window.I18N = window.I18N || {};
window.I18N.zh = {
  eyebrow: '工作面板',
  title: '程序员任务管理器',
  assistantTitle: 'AI 助手',
  apiKeyLabel: 'API 密钥',
  apiKeyPlaceholder: '如果有，请输入 API 密钥',
  promptPlaceholder: '输入你的请求...',
  askBtn: '询问助手',
  suggestBtn: '任务建议',
  assistantDefaultResponse: '我会帮助你整理任务并规划执行。',
  addTaskTitle: '添加新任务',
  taskTitleLabel: '任务标题',
  taskTitlePlaceholder: '例如：修复支付界面错误',
  taskDescriptionLabel: '描述',
  taskDescriptionPlaceholder: '写下任务细节或期望结果...',
  priorityLabel: '优先级',
  priorityHigh: '高',
  priorityMedium: '中',
  priorityLow: '低',
  categoryLabel: '类别',
  categoryFeature: '功能',
  categoryBug: '错误',
  categoryResearch: '研究',
  categoryTest: '测试',
  categoryRefactor: '重构',
  dueDateLabel: '截止日期',
  addTaskBtn: '添加任务',
  taskListTitle: '任务列表',
  searchPlaceholder: '快速搜索...',
  filterAll: '全部',
  filterPending: '进行中',
  filterDone: '已完成',
  filterHigh: '高优先级',
  statTotal: '总数',
  statDone: '已完成',
  statPending: '剩余',
  statProgress: '进度',
  emptyStateTitle: '没有任务符合当前搜索条件',
  emptyStateText: '试试其他类别或新增任务。',
  noDescription: '没有附加说明。',
  noDate: '无日期',
  completeTask: '完成',
  reopenTask: '重新打开',
  deleteTask: '删除',
  toggleAria: '切换任务状态',
  languageLabel: '语言',
  other: '其他',
  noTasks: '没有任务',
  currentTasks: '当前任务',
  askFirst: '请先写下你的问题或请求。',
  preparingAssistant: '正在准备助手回复...',
  assistantUnavailable: '助手当前不可用，将使用本地版本。',
};
